version: '3.8'

services:
  production-service:
    image: nginx:latest
    container_name: production-service
    ports:
      - "8080:80"
    volumes:
      - ./production-service:/usr/share/nginx/html

  shadow-service:
    image: nginx:latest
    container_name: shadow-service
    ports:
      - "8081:80"
    volumes:
      - ./shadow-service:/usr/share/nginx/html

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
